name: enfo
description: Enfo, a minimalistic pomodoro timer for distracted people.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  percent_indicator: ^4.2.3
  animations: ^2.0.7
  circular_countdown_timer: ^0.2.3
  adaptive_theme: ^3.2.1
  shared_preferences: ^2.1.1
  local_notifier: ^0.1.5
  window_manager: ^0.3.2
  flutter_local_notifications: ^14.0.0+1
  permission_handler: ^10.2.0
  animated_text_kit: ^4.2.2
  introduction_screen: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true